CURRENCIES_LIST = [{'character_code': 'AUD', 'name': 'Австралийский доллар'},
                 {'character_code': 'ATS', 'name': 'Австрийский шиллинг'},
                 {'character_code': 'AZN', 'name': 'Азербайджанский манат'},
                 {'character_code': 'GBP', 'name': 'Фунт стерлингов Соединенного королевства'},
                 {'character_code': 'AON', 'name': 'Ангольская новая кванза'},
                 {'character_code': 'AMD', 'name': 'Армянский драм'},
                 {'character_code': 'BYN', 'name': 'Белорусский рубль'},
                 {'character_code': 'BEF', 'name': 'Бельгийский франк'},
                 {'character_code': 'BGN', 'name': 'Болгарский лев'},
                 {'character_code': 'BRL', 'name': 'Бразильский реал'},
                 {'character_code': 'HUF', 'name': 'Венгерский форинт'},
                 {'character_code': 'HKD', 'name': 'Гонконгский доллар'},
                 {'character_code': 'GRD', 'name': 'Греческая драхма'},
                 {'character_code': 'DKK', 'name': 'Датская крона'},
                 {'character_code': 'USD', 'name': 'Доллар США'},
                 {'character_code': 'EUR', 'name': 'Евро'},
                 {'character_code': 'INR', 'name': 'Индийская рупия'},
                 {'character_code': 'IEP', 'name': 'Ирландский фунт'},
                 {'character_code': 'ISK', 'name': 'Исландская крона'},
                 {'character_code': 'ESP', 'name': 'Испанская песета'},
                 {'character_code': 'ITL', 'name': 'Итальянская лира'},
                 {'character_code': 'KZT', 'name': 'Казахстанский тенге'},
                 {'character_code': 'CAD', 'name': 'Канадский доллар'},
                 {'character_code': 'KGS', 'name': 'Киргизский сом'},
                 {'character_code': 'CNY', 'name': 'Китайский юань'},
                 {'character_code': 'KWD', 'name': 'Кувейтский динар'},
                 {'character_code': 'LVL', 'name': 'Латвийский лат'},
                 {'character_code': 'LBP', 'name': 'Ливанский фунт'},
                 {'character_code': 'LTL', 'name': 'Литовский лит'},
                 {'character_code': 'MDL', 'name': 'Молдавский лей'},
                 {'character_code': 'DEM', 'name': 'Немецкая марка'},
                 {'character_code': 'DEM', 'name': 'Немецкая марка'},
                 {'character_code': 'NLG', 'name': 'Нидерландский гульден'},
                 {'character_code': 'NOK', 'name': 'Норвежская крона'},
                 {'character_code': 'PLN', 'name': 'Польский злотый'},
                 {'character_code': 'PTE', 'name': 'Португальский эскудо'},
                 {'character_code': 'ROL', 'name': 'Румынский лей'},
                 {'character_code': 'RON', 'name': 'Румынский лей'},
                 {'character_code': 'XDR', 'name': 'СДР (специальные права заимствования)'},
                 {'character_code': 'SGD', 'name': 'Сингапурский доллар'},
                 {'character_code': 'SRD', 'name': 'Суринамский доллар'},
                 {'character_code': 'TJS', 'name': 'Таджикский сомони'},
                 {'character_code': 'TJR', 'name': 'Таджикский рубл'},
                 {'character_code': 'TRY', 'name': 'Турецкая лира'},
                 {'character_code': 'TMM', 'name': 'Туркменский манат'},
                 {'character_code': 'TMT', 'name': 'Новый туркменский манат'},
                 {'character_code': 'UZS', 'name': 'Узбекский сум'},
                 {'character_code': 'UAH', 'name': 'Украинская гривна'},
                 {'character_code': 'FIM', 'name': 'Финляндская марка'},
                 {'character_code': 'FRF', 'name': 'Французский франк'},
                 {'character_code': 'CZK', 'name': 'Чешская крона'},
                 {'character_code': 'SEK', 'name': 'Шведская крона'},
                 {'character_code': 'CHF', 'name': 'Швейцарский франк'},
                 {'character_code': 'XEU', 'name': 'ЭКЮ'},
                 {'character_code': 'EEK', 'name': 'Эстонская крона'},
                 {'character_code': 'YUN', 'name': 'Югославский новый динар'},
                 {'character_code': 'ZAR', 'name': 'Южноафриканский рэнд'},
                 {'character_code': 'KRW', 'name': 'Вон Республики Корея'},
                 {'character_code': 'JPY', 'name': 'Японская иена'}]


CURRENCIES_CHAR_CODES = ['AUD', 'ATS', 'AZN', 'GBP', 'AON', 'AMD', 'BYN', 'BEF', 'BGN', 'BRL', 'HUF', 'HKD', 'GRD',
                         'DKK', 'USD', 'EUR', 'INR', 'IEP', 'ISK', 'ESP', 'ITL', 'KZT', 'CAD', 'KGS', 'CNY', 'KWD',
                         'LVL', 'LBP', 'LTL', 'MDL', 'DEM', 'DEM', 'NLG', 'NOK', 'PLN', 'PTE', 'ROL', 'RON', 'XDR',
                         'SGD', 'SRD', 'TJS', 'TJR', 'TRY', 'TMM', 'TMT', 'UZS', 'UAH', 'FIM', 'FRF', 'CZK', 'SEK',
                         'CHF', 'XEU', 'EEK', 'YUN', 'ZAR', 'KRW', 'JPY']
